### ISSUE TITLE
読んでるときのログのログ

### ISSUE THREAD

**Issue by orzup** [orzup/rails-tutorial#1]
ログだ！

**Comment by orzup** [comment]
# 2015/06/09

![2015-06-09 14 45 37](https://cloud.githubusercontent.com/assets/1712281/8051363/60fd9fc4-0eb6-11e5-8de3-5e47e86167d4.jpg)
![2015-06-09 15 46 55](https://cloud.githubusercontent.com/assets/1712281/8052104/de00b364-0ebe-11e5-85b9-bb7deb041c64.jpg)
![2015-06-09 18 48 53](https://cloud.githubusercontent.com/assets/1712281/8055131/5092a1e4-0ed8-11e5-8770-ebd6709096cb.jpg)

**Comment by orzup** [comment]
# 1.1
![2015-06-09 15 46 55](https://cloud.githubusercontent.com/assets/1712281/8052104/de00b364-0ebe-11e5-85b9-bb7deb041c64.jpg)

**Comment by orzup** [comment]
![2015-06-09 18 48 53](https://cloud.githubusercontent.com/assets/1712281/8055131/5092a1e4-0ed8-11e5-8770-ebd6709096cb.jpg)

**Comment by orzup** [comment]
# 2015/06/10

![2015-06-10 14 55 24](https://cloud.githubusercontent.com/assets/1712281/8075929/0cdd3410-0f81-11e5-8337-28fc04a592af.jpg)
![2015-06-10 15 31 08](https://cloud.githubusercontent.com/assets/1712281/8076327/13e7ace0-0f86-11e5-9560-986eea74be70.jpg)

**No real understanding No real understanding No real understanding No real understanding**

**Comment by hiboma** [comment]
このログいいね :+1:

**Comment by orzup** [comment]
自分のことばでまとめると、よく頭に入ることに気がつきました:eyes:

**Comment by ku00** [comment]
ログのログだ :eyes:

**Comment by orzup** [comment]
# 2015/06/11

![2015-06-11 17 09 04](https://cloud.githubusercontent.com/assets/1712281/8102663/d194e1c8-105c-11e5-89ba-b3121a8e162f.jpg)

**Comment by ryoma123** [comment]
> 自分のことばでまとめると、よく頭に入ることに気がつきました:eyes:

素晴らしい！手書きなのもよいね〜:+1:

**Comment by orzup** [comment]
図がササっとかけるので、とてもよいです！:oden:

**Comment by orzup** [comment]
# 2015/06/12

![image](https://cloud.githubusercontent.com/assets/1712281/8126267/ed4e2e8a-1127-11e5-965b-e9587b10aaef.png)

**Comment by hfm** [comment]
これはすばらし～ :+1:

**Comment by udzura** [comment]
asset pipelineの図とかちょういい

**Comment by yutokyokutyo** [comment]
勉強になります！！！１

**Comment by takatoshiono** [comment]
めっちゃいい

**Comment by orzup** [comment]
# 2015/06/15

![img_6273](https://cloud.githubusercontent.com/assets/1712281/8155449/5566b128-137f-11e5-9c5d-19992990ef15.JPG)

**Comment by Joe-noh** [comment]
暗号化とハッシュ化は区別しないと、怖い人に怒られるぞ！

**Comment by kenchan** [comment]
神スレだ

**Comment by orzup** [comment]
> 暗号化とハッシュ化は区別しないと、怖い人に怒られるぞ!

やばい、ちゃんと調べないと消される…！

**Comment by orzup** [comment]
改訂版
![img_6275](https://cloud.githubusercontent.com/assets/1712281/8157317/ddca6e9c-138e-11e5-87f7-69d60c5f605c.JPG)

**Comment by orzup** [comment]
# 2015/06/16

![img_6282](https://cloud.githubusercontent.com/assets/1712281/8179480/d8ff0eea-1451-11e5-8f86-9ff733057fae.JPG)

**Comment by orzup** [comment]
# 2015/06/17

![img_6290](https://cloud.githubusercontent.com/assets/1712281/8204900/144e08ea-1527-11e5-89c8-cdcd81399b47.JPG)

**Comment by inouetakuya** [comment]
ほうほう

**Comment by orzup** [comment]
# 2015/06/18

![img_6302](https://cloud.githubusercontent.com/assets/1712281/8227158/b434b5da-15df-11e5-8e54-31812572b8d6.JPG)
（新しい知識よりも実装部分で悩むことが多い日でした）

**Comment by orzup** [comment]
# 2015/06/19

![img_6315](https://cloud.githubusercontent.com/assets/1712281/8251251/ec0da33c-16b5-11e5-8496-ba4da359277e.JPG)

**Comment by orzup** [comment]
# 2015/06/22

![img_6539](https://cloud.githubusercontent.com/assets/1712281/8279440/ab84e666-190f-11e5-8926-141e7fb68a84.JPG)
だんだん1章につき2日はかかりはじめてる（それから誤字が多い）

**Comment by orzup** [comment]
# 2015/06/23

![img_6542](https://cloud.githubusercontent.com/assets/1712281/8303320/1089a9f2-19d8-11e5-952d-bac5e8039d11.JPG)

**Comment by orzup** [comment]
# 2015/06/24

![img_6548](https://cloud.githubusercontent.com/assets/1712281/8327598/a137c944-1aa4-11e5-903e-c4999c06387a.JPG)

**Comment by orzup** [comment]
# 2015/06/25

実装部分で悩む日だったので今日はなし。また明日！

**Comment by orzup** [comment]
# 2015/06/26

![img_6555](https://cloud.githubusercontent.com/assets/1712281/8375633/174c9664-1c3a-11e5-92f1-6837f0ec4491.JPG)
（進みがよろしくない）

**Comment by orzup** [comment]
# 2015/06/29

![img_6619](https://cloud.githubusercontent.com/assets/1712281/8405940/1cee5d68-1e93-11e5-913a-5948b777d6e4.JPG)
チート(joe)つかった

**Comment by orzup** [comment]
# 2015/06/30

![img_6632](https://cloud.githubusercontent.com/assets/1712281/8428261/5bdc753a-1f58-11e5-82e0-0232288bb757.JPG)
![img_6633](https://cloud.githubusercontent.com/assets/1712281/8428264/5f012954-1f58-11e5-90f3-6c9cfaebe847.JPG)

**Comment by orzup** [comment]
# 2015/07/01

![img_6636](https://cloud.githubusercontent.com/assets/1712281/8452244/204f6abe-2024-11e5-9278-6080c7f2010d.JPG)

**Comment by orzup** [comment]
# 2015/07/02

![img_6642](https://cloud.githubusercontent.com/assets/1712281/8471116/043cc50e-20d0-11e5-9609-122d00eff18f.JPG)

**Comment by hiboma** [comment]
だーん !!!

**Comment by murasakipinko** [comment]
すげーいい！

**Comment by shikakun** [comment]
かっこいい！

**Comment by inouetakuya** [comment]
:tada:

**Comment by udzura** [comment]
:congratulations:

**Comment by orzup** [comment]
わいわい！無事に学んだことの振り返りも終えたのでこのissueは閉じます！
ブログにまとめるぞ〜！:sunglasses:
